### ISSUE TITLE
Test workflow not running in pr-open Github Action

### ISSUE THREAD

**Issue by tobiasmllr** [bcgov/nr-hydrometric-rating-curve#105]
@DerekRoberts Thank you for fixing the earlier problems! Now I see that my testing step does not run correctly. Could you give me a hint how I can execute a test from within the deployed docker container?

You can see the error in the failed step of https://github.com/bcgov/nr-hydrometric-rating-curve/pull/102
```
Run docker exec -it rctool /bin/bash -c "python manage.py test"
Error response from daemon: No such container: rctool
Error: Process completed with exit code 1.
```

This is my Tests step, basically I just want to run `python manage.py test` from within the rctool docker container
```
  tests:
    name: Run Tests for Django App
    needs: [deploys]
    runs-on: ubuntu-22.04
    steps:
      - name: Run Django Tests in frontend docker container
        run: |
          docker exec -it rctool /bin/bash -c "python manage.py test"
```
